### ISSUE TITLE
frame-page directive body extends past footer

### ISSUE THREAD

**Issue by timlevett** [UW-Madison-DoIT/uw-frame#152]
![http://goo.gl/L4nOg9](http://goo.gl/L4nOg9)

**Comment by vertein** [comment]
gross

**Comment by timlevett** [comment]
totes

**Comment by jhanstra** [comment]
is this under /web rendering? There were several of these cases when I was testing

**Comment by timlevett** [comment]
yeah, i think its because of the `<frame-page>` body being background-white. We did a trick to get it centered, that may be the issue
