### ISSUE TITLE
z-indexes are too big

### ISSUE THREAD

**Issue by timlevett** [UW-Madison-DoIT/uw-frame#175]
Right now we have high `z-indexes`, like in the thousands. Lets trim those out a bit or remove if not needed.

**Comment by jhanstra** [comment]
I don't think having such high z-indexes is that silly or unusual, but I do think they are currently very unorganized and it's hard to understand where a z-index ranks relative to other elements on the page. 

This article gives some good ideas for dealing with z-index that we might model: https://css-tricks.com/handling-z-index/

**Comment by timlevett** [comment]
One could also suggest looking at something like this: https://www.google.com/design/spec/what-is-material/elevation-shadows.html

**Comment by paulerickson** [comment]
![the z-indexes are too damn high](https://i.imgflip.com/1062y9.jpg)

**Comment by timlevett** [comment]
lolz @paulerickson

**Comment by vertein** [comment]
z-indexes brought under control in the 2.7.0 in the 2.7.0 release.

**Comment by jhanstra** [comment]
👍 hi @vertein
