### ISSUE TITLE
Screenreader not picking up on account dropdown

### ISSUE THREAD

**Issue by jjones770** [UW-Madison-DoIT/uw-frame#211]
When using VoiceOver or NVDA, the screenreader is not "seeing" the account dropdown menu (the user's name and carrot, and corresponding menu).

**Comment by timlevett** [comment]
Playing around with https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn I was able to recreate.

**Comment by apetro** [comment]
Backlogged as [MUMUP-2508](https://jira.doit.wisc.edu/jira/browse/MUMUP-2508).

**Comment by vertein** [comment]
Fixed in the 2.7.0 release.
