### ISSUE TITLE
Links in sidebar do not produce desired result.

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/uw-frame#23]
We have an app that has attempted to customize the links in the sidebar, here is the content of our app's samples/sidebar.json:

```
{"sidebar" :  
            [
                {"title": "Home", "hyperlink" : "/", "target" : "", "faIcon" : "fa-home", "displayFlag" : ""},
                {"title": "Leave Statement", "hyperlink" : "https://my.wisc.edu/portal/p/leave-statement", "target" : "", "faIcon" : "fa-external-link", "displayFlag" : ""},
                {"title": "Log out", "hyperlink" : "/logout", "target" : "", "faIcon" : "fa-sign-out", "displayFlag" : ""}
            ]
}
```

The link titled 'Log out' is the subject of this issue. The links to Home and Leave Statement produce the desired effect; the former goes to the root of the app, the latter takes us to the external site.

Clicking Log out produces a result similar to what the Home link provides. Here is a gif of the issue:

![logout](https://cloud.githubusercontent.com/assets/1041730/9795958/29bb9b6e-57b9-11e5-9a2d-ddb11d9e6b81.gif)

The Network tab of Developer tools shows the XMLHttpRequests we would expect if the Home view was selected. The href of the a tag in the sidebar includes the desired /logout value, however perhaps something is intercepting the onClick event and sending us to / instead?

**Comment by timlevett** [comment]
Have you set the route correctly in your web.xml (or your java config)?

**Comment by nblair** [comment]
/logout isn't an angular route, it's a Spring WebMVC controller (provided by Spring Security).

**Comment by nblair** [comment]
Looking at src/main/webapp/my-app/main.js, I may have my answer:

```
$routeProvider....
  otherwise(main);
```

/logout is being seen as an angular route, and routeProvider doesn't have anything mapped, so we end up at home.

Seems like I need to configure the routeProvider for /logout anyways?

**Comment by nblair** [comment]
Found my answer, the trick is to change the samples/sidebar.json to:

> {"title": "Log out", "hyperlink" : "/logout", **"target" : "_self"**, "faIcon" : "fa-sign-out", "displayFlag" : ""}

Reference: http://eli.eliandlyndi.com/2013/08/26/navigate-urls-angular-application-target_self/

**Comment by timlevett** [comment]
Cool! That is great insight @nblair. Makes sense.
