### ISSUE TITLE
Hover color on widgets in compact view not using theme colors

### ISSUE THREAD

**Issue by JoyceJohnston** [UW-Madison-DoIT/uw-frame#262]
When you hover on a widget in compact view, the hover color is UW-Madison red, rather than a theme color.
![screen shot 2016-08-05 at 9 50 25 am 2](https://cloud.githubusercontent.com/assets/16137251/17440525/8e2213b6-5af2-11e6-9209-078d72d9ff87.png)

**Comment by apetro** [comment]
Backlogged, prioritized for Scrum purposes as [MUMUP-2648](https://jira.doit.wisc.edu/jira/browse/MUMUP-2648).

**Comment by timlevett** [comment]
This may just be an issue in angularjs-portal

**Comment by timlevett** [comment]
Fixed in 2.5.0
