### ISSUE TITLE
Header disappears when clicking the down-caret next to name if scroll position is not at the top

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/uw-frame#289]
Using release 2.6.1.

If you scroll down, then click the down-caret next to your name, the log out button appears, but the header disappears.

This behavior does not occur if you are scrolled to the top.

Example:

![frame-logout](https://cloud.githubusercontent.com/assets/1041730/17985607/2fc99b46-6adc-11e6-9dd4-88591a6c139f.gif)

**Comment by timlevett** [comment]
I can recreate this on the docs page (http://uw-madison-doit.github.io/uw-frame/latest/)

**Comment by timlevett** [comment]
Created https://jira.doit.wisc.edu/jira/browse/MUMUP-2703 to track in the Jira

**Comment by thevoiceofzeke** [comment]
PR ready: https://github.com/UW-Madison-DoIT/uw-frame/pull/295
