### ISSUE TITLE
Fails to load when a theme is specified with uw-frame 2.9.0

### ISSUE THREAD

**Issue by paulerickson** [UW-Madison-DoIT/uw-frame#333]
Working on uw-digital-id-app, I had OVERRIDE.APP_FLAGS.defaultTheme set to 'uw-system', but when I upgraded from uw-frame 2.8.0 to 2.9.0 it stopped loading.

Javascript throws an `Uncaught TypeError: Cannot read property 'name' of undefined` from uw-frame-components/portal/main.js:176
```javascript
174       var generateTheme = function(name) {
175         if(!name) {
176           name = $rootScope.portal.theme.name;
177         }
178         $rootScope.portal.theme.themeVersion = THEMES.themeVersion;
179         var mdTheme = $mdTheming.THEMES[name];
180         if(mdTheme) {
181           $mdTheming.generateTheme(name,null);
182         }
183       };
```

![screenshot from 2016-10-10 10-58-29](https://cloud.githubusercontent.com/assets/50889/19242542/44c11256-8ed9-11e6-84e4-d5a3170fe9f3.png)

As a workaround, I'm just removing the defaultTheme configuration from my app.

**Comment by apetro** [comment]
Backlogged as [MUMMNG-2897](https://jira.doit.wisc.edu/jira/browse/MUMMNG-2879) for Scrum purposes.
