### ISSUE TITLE
No Log Out link available when showSidebar=false

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/uw-frame#34]
As a person interacting with a frame app with `APP_FLAGS.showSidebar : false` in `js/app-config.js` I want to be able to find a log out link so that I can log out.

**Comment by apetro** [comment]
Interesting point.  When `.showSidebar` is set to false, the logout link should probably be rendered somewhere else in the UI where users expect to find it.  Upper right, maybe.

**Comment by nblair** [comment]
:+1:

**Comment by timlevett** [comment]
I kind of want a profile thingy (kind of like github has). Thoughts?

![http://goo.gl/9xc9Fu](http://goo.gl/9xc9Fu)

**Comment by apetro** [comment]
I think an upper right profile menu is a great idea, but one to grow into. Might be able to get away with just a logout link as the very simplest first step.  Iterate from there?

**Comment by timlevett** [comment]
Just thinking, sidebar hidden also has the disadvantage of losing who you are

**Comment by apetro** [comment]
Absolutely.  I'm agreeing with the spirit of this 100%. And the details of that GitHub profile menu are awesome, in that this solves our cramming your really-long-name into the space by *not* displaying the name, just displaying a fixed-size picture, with the name tucked into the menu.  I do think this profile menu in the upper right would solve some real needs for MyUW. It's a great idea. But still feeling like going after it iterateively. :repeat:

**Comment by timlevett** [comment]
Agreed

**Comment by keirserrie** [comment]
:+1: to upper-right profile, this is standard and expected at this point. Upper right logout link fine for now. Also iterative approach seems like the only possible approach.

**Comment by nblair** [comment]
:+1: on iterative approach.

**Comment by apetro** [comment]
Backlogged the logout link increment of progress as [MUMUP-2156](https://jira.doit.wisc.edu/jira/browse/MUMUP-2156).

**Comment by timlevett** [comment]
Fixed :)
