### ISSUE TITLE
Frame build should be OS platform independent

### ISSUE THREAD

**Issue by vertein** [UW-Madison-DoIT/uw-frame#349]
Developers using windows can not build uw-frame

**Comment by vertein** [comment]
Tracked internally via JIRA story [MUMUP-2798](https://jira.doit.wisc.edu/jira/browse/MUMUP-2798)

**Comment by ChristianMurphy** [comment]
related aside: [AppVeyor](https://www.appveyor.com/) can be helpful for automating Windows testing.

**Comment by ChristianMurphy** [comment]
@vertein are Windows builds still an issue?
AppVeyor CI has been reporting Windows builds as passing https://ci.appveyor.com/project/vertein/uw-frame/history.

**Comment by vertein** [comment]
Thanks for following up on this issue.  This issue can be closed.  Thanks for the work you did!
