### ISSUE TITLE
Upgrade to AngularJS 2+?

### ISSUE THREAD

**Issue by xdhmoore** [UW-Madison-DoIT/uw-frame#389]
Hi,

Are there any plans to upgrade to Angular 2 or higher? Our team is evaluating our uportal options in light of the removal of portlet support in Spring 5.

**Comment by vertein** [comment]
Hello!  Thanks for the issue.  We are planning to upgrade to a new version of Angular.  Two active committers are attending [ng-confg](https://www.ng-conf.org/) right now.  We'll be leaning on their new experience during the upgrade.  We have the upgrade tentatively planned in the next couple of months.

This project is currently [incubating in Apereo](https://www.apereo.org/projects/angularjs-portal).  We're planning on giving quite a few presentations at [Open Apereo 2017](https://www.apereo.org/conferences/open-apereo-2017).  If you're able to attend and want to talk in person about the future of uPortal, we'd be excited to meetup or if you would like to talk more on the uPortal developer email list ( uportal-dev@apereo.org), that's open as well. 

Feel free to reach out if you have any other questions!

**Comment by xdhmoore** [comment]
Thanks for the fast respone. I'm actually on the mailing list already, though my participation has been minimal. I do have some further questions though. I'll ask them there.

**Comment by apetro** [comment]
(Closed issue, figuring the question is answered.  Please do get in touch in any way that works when there's more to discuss, about this or anything else.)
