### ISSUE TITLE
Disable Coveralls comments

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/uw-frame#401]
Currently for every commit Coveralls both:

Adds a comment for the commit:
![comment](https://cloud.githubusercontent.com/assets/3107513/24426769/94a7693c-13bd-11e7-9b50-b68cabddaf26.png)

And reports to the PR status:
![pr-status](https://cloud.githubusercontent.com/assets/3107513/24426795/a63bbfea-13bd-11e7-9bd6-b2cd2998366d.png)
![maintained-for-commits](https://cloud.githubusercontent.com/assets/3107513/24426959/2efedea2-13be-11e7-8737-8f5b4b876a32.png)

Disabling the comment mechanism could keep PRs easier to read.

Related to https://github.com/UW-Madison-DoIT/angularjs-portal/issues/607

**Comment by apetro** [comment]
[Done|https://goo.gl/VkVyZF].

**Comment by ChristianMurphy** [comment]
Thanks @apetro !
