### ISSUE TITLE
Enable AppVeyor Builds

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/uw-frame#437]
Follow up on #408

[AppVeyor is configured for the repository](https://github.com/UW-Madison-DoIT/uw-frame/blob/7bae5d0008f4c07c0909f75c2002c6b7668f7be6/appveyor.yml), however a repository admin would need to go to <https://ci.appveyor.com/projects/new> and flip the switch for the automated Windows builds to happen.

**Comment by vertein** [comment]
I think I flipped the bit.  I guess we'll see on the next pull request.

**Comment by vertein** [comment]
Yep, it's working.
