### ISSUE TITLE
Static build broken (again)

### ISSUE THREAD

**Issue by thevoiceofzeke** [UW-Madison-DoIT/uw-frame#481]
The static build is currently broken. See screenshots of terminal output and result:

<img width="1065" alt="screen shot 2017-07-26 at 12 26 50 pm" src="https://user-images.githubusercontent.com/5818702/28634738-c90eb0ce-71fd-11e7-979f-05856b92ce64.png">
<img width="930" alt="screen shot 2017-07-26 at 12 27 03 pm" src="https://user-images.githubusercontent.com/5818702/28634737-c90d0eae-71fd-11e7-9a7f-0a4174df0394.png">

My best guess is it was caused by a recent pull request (#474). I haven't dug into this yet, but wanted to record for visibility.

**Comment by thevoiceofzeke** [comment]
Note to future self: Remove node_modules and npm install when dependencies are updated

**Comment by davidmsibley** [comment]
This was due to npm apparently not doing the right thing on the upgrade. Fixed by removing `node_modules` folder
