### ISSUE TITLE
Two 4.1.0 Releases?

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/uw-frame#488]
Looking through the releases I noticed there are two 4.1.0 releases on different commits

1. https://github.com/UW-Madison-DoIT/uw-frame/releases/tag/v4.1.0
2. https://github.com/UW-Madison-DoIT/uw-frame/releases/tag/uw-frame-maven-4.1.0

Is that intended?

**Comment by apetro** [comment]
Looks like the former was promoted from mere tag to release in error. Deleted that release, demoting it to just a tag.

**Comment by ChristianMurphy** [comment]
Follow up question looking through tags, there appears to be a consistent pattern of tagging both:

`uw-frame-maven-{semver-version-number}`
and
`v{semver-version-number}`

Is that also intended?

**Comment by apetro** [comment]
Two release tags is result of releasing each release twice, once [to npm](https://github.com/UW-Madison-DoIT/uw-frame/blob/master/docs/releasing.md#node-release) and once to [Maven OSS Central](https://github.com/UW-Madison-DoIT/uw-frame/blob/master/docs/releasing.md#java-release). Someday we'll mature to `uw-frame` not being a Java artifact and no longer adopting it in frame-based apps via Maven Overlay.

**Comment by ChristianMurphy** [comment]
Thanks @apetro!
