### ISSUE TITLE
'Log out' URL defined in 2 places

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/uw-frame#51]
In 1.2.0 release, there are 2 configuration locations for a 'Log out' URL:

1. in staticFeeds/sidebar.json.
2. in js/app-config.js (`MISC_URLS.logoutURL`)

Is there any way those can be consolidated?

**Comment by nblair** [comment]
I personally prefer the former method, in the sidebar, because it allows for additional configuration. Of particular importance is the `target` attribute.
Say you need to configure `MISC_URLS.logoutURL` to be a path that is **not** an angular route. In order to signal the angular router to do the right thing, once must set a target attribute of '_self'; otherwise the router will try to handle the path, and not having a route mapping, will fall through to the default route.

For example, 'logout' is not a route, it's a path. If I change `MISC_URLS.logoutURL` to logout, angular can't find the route, and sends me to the home view in my app, not logout.

**Comment by timlevett** [comment]
How would one know that the final array item in `sidebar.json` is the logout link? Seems a bit hacky to me. Is having it defined in 2 spots really the problem? or rather that we didn't provide a variable to set the target value? Could just change the `MISC_URLS.logoutURL` to `LOGOUT_CONFIG` with keys `url` and `target`. Would that solve your delema?

Additionally we could enhance the sidebar to take in constants as hrefs. Also seems a bit hacky.

**Comment by nblair** [comment]
Both approaches seem legit to me; I think as is `MISC_URLS.logout`~~URL~~ should be an object like you described.

**Comment by nblair** [comment]
I feel like having to define Log out in sidebar.json is unnecessary. Same for Home.

Perhaps both of those URLs come in through `MISC_URLS`, are not overridable, and then we are left to inject our own URLs that land in between (like the popular 'Leave Statement' URL from STAR)?

**Comment by nblair** [comment]
Per gitter, I'm going to take a stab at this.
