### ISSUE TITLE
Discussion: Enable protected branches and required checks

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/uw-frame#528]
Github required checks help to manage the code review and quality process.

### Impact

* `master` branch cannot have commits removed, revert commits must be used
* Pull request must be in sync with master branch before merging
* Branches would need to have at least approving review and no changes requested
  + :notebook: administrators can bypass this, but will be given an extra confirmation to bypass
  + https://help.github.com/articles/about-required-reviews-for-pull-requests/
* Branches would need to have CI and dependency checks report back as passing before merge
  + :notebook: administrators can bypass this, but will be given an extra confirmation to bypass
  + https://help.github.com/articles/about-required-status-checks/

![uw-frame-protected master-branch](https://user-images.githubusercontent.com/3107513/30496946-e30d2a0c-9a05-11e7-867d-07621984c537.png)

**Comment by vertein** [comment]
+1

**Comment by ChristianMurphy** [comment]
Added
