### ISSUE TITLE
Thought experiment: compiled uw-frame deliverables

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/uw-frame#57]
As a developer
I regularly need to provide dynamic REST APIs that are configured as providers for the `SERVICE_LOC` fields (sessionInfo, sidebarInfo)
so that the values returned by those providers can vary dependent on authenticated user/server environment/time of day/whatever.

In 2 uw-frame applications we've written, we have twice needed to make back end programming language representations of the data objects presented by sessionInfo and sidebarInfo.

Example:

```java
/**
   * Bean matching data model represented by /staticFeeds/session.json.
   * 
   * @author Nicholas Blair
   */
  public class Person {

    private final String username;
    private final String sessionKey = "";
    private final String serverName = "";
    private final String displayName;
    private final Build build;

    public Person(Environment environment, String username, String displayName) {
      this.username = username;
      this.displayName = displayName;
      this.build =  new Build(environment.getProperty(GIT_COMMIT_ID_ABBREV), environment.getProperty(GIT_BRANCH), environment.getProperty(PROJECT_VERSION), environment.getProperty(GIT_TAGS));
    }

// ...truncated for brevity
}
```

```java
/**
   * Bean matching model presented by /staticFeeds/sidebar.json
   * 
   * @author Nicholas Blair
   */
  public class Sidebar {
    private String title = "";
    private String hyperlink = "";
    private String target = "";
    private String faIcon = "";
    private String displayFlag = "";
    /**
     * @return the title
     */
    public String getTitle() {
      return title;
    }
// ... truncated for brevity
}
```

2 times I've had to copy these same classes into 2 apps. In the interest of [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), it would be nice to have some project, preferably with an established dependency relationship with this project, including tests that guarantee we don't regress incompatible data model changes between the 2 projects, that provides compiled artifacts that represent these objects, so that I don't have to copy them into each app project that needs them.

I'm opening this to start a discussion on how we might deliver artifacts like this. Would we make this multi-module? Would we make them separate projects? Would we do this in uw-frame, and ship a classes jar (I'm :-1: on this)? What about other programming languages, like Go and PHP?

**Comment by timlevett** [comment]
I like the idea of supporting this, I also like the idea of supporting multiple languages. Goes toward my vision of a [bower module for uw-frame](https://gist.github.com/timlevett/39bf7ea5bcb70266d63b). What about [protobuffers?](https://developers.google.com/protocol-buffers/). 

Another idea is just to put those model objects in a class somewhere.

**Comment by nblair** [comment]
The *somewhere* is really what I'm asking for. I don't think it would go in the current war deliverable that uw-frame ships now, it wouldn't be usable. We would have to publish a classes jar for uw-frame too, which can have some quirks in downstream app assembly.

Where would we put the protobuffer deliverables? In the uw-frame war? How would a downstream Java app reference them for say a Spring WebMVC `@RestController`? How about a downstream PHP or Go app?

**Comment by timlevett** [comment]
Create a module in `app-seed`, `uw-frame-utils` project?

**Comment by timlevett** [comment]
I kind of feel like if it is a separate repo, it might get forgotten, unless we are really on top of it. How are you maintaining the classes now? Just looking at diffs when upgrading frame?

**Comment by nblair** [comment]
Those classes currently are in their respective app projects.

If uw-frame is characterized as the 'java solution for frame based projects', then I think going multi-module is the appropriate approach. But, if uw-frame is not just for java projects (and I think that's on the roadmap, with our look at alternatives like Go and PHP), then I'm hesitant to think multi-module is the right answer. The non-java projects will need so pull in frame using something like bower. The java projects could do this too.

**Comment by timlevett** [comment]
My thought on the multi lang support would be transition the repo `uw-frame` to be `uw-frame-java`, then create a `uw-frame-angular-components` or something like that. 

We could also just have one repo to rule them all:
```
uw-frame
 - uw-frame-java-webapp (creates the war that is deployed to maven central)
 - uw-frame-angular-components (creates the uw-frame bower component that is deployed to bower)
 - uw-frame-protobuf (using the protocol buffer compiler, could generate a jar)
 - ...etc... 
```

**Comment by paulerickson** [comment]
I like the idea of making uw-frame multi-module with, e.g., a new `uw-frame-api` becoming a dependency of `uw-frame`, containing interfaces that a given app can implement.

The key is that an `-api` module is a common dependency of both server and client, but that's not possible to include non-java languages without something special like protobuf.  IMHO, I would go with a plain ol' java solution until other language implementations actually exist.

**Comment by nblair** [comment]
I like the one repo approach you've laid out there, :+1: 

Tucking other - even non Java - projects as siblings of uw-frame-protobuf could be accomplished too.

**Comment by timlevett** [comment]
Cool, so i think we have a good path forward. We have already migrated to a multimodule project. Feel free to add model objects to uw-frame-java as you see fit. I'm going to close this thought experiment as a success. Thanks!
