### ISSUE TITLE
ngView animations

### ISSUE THREAD

**Issue by smargovsky** [UW-Madison-DoIT/uw-frame#60]
Greetings folks,

Before a pull request comes your way, I wanted to run this by the larger group.  We have a need to animate one and only one ( so far ) route change via ng-animate.  This is very doable, but targeting a specific route only becomes much trickier.  It **could** be simpler by appending the route as a class to ng-view.  

Thoughts?

Other suggestions to target only specific route changes ( w/o an additional directive that requires defining animations at the ng-route level )?

**Comment by timlevett** [comment]
Neat, I could see having a `{{pageClass}}` as being a viable solution.

I saw this tutorial, seemed pretty easy: https://scotch.io/tutorials/animating-angularjs-apps-ngview

**Comment by smargovsky** [comment]
:+1: exactly what I had in mind.
