### ISSUE TITLE
Where to put documentation about directives?

### ISSUE THREAD

**Issue by timlevett** [UW-Madison-DoIT/uw-frame#72]
Hey All,

I want to create documentation about all the directives, services, etc... that we have. Kind of a "here is how you use that". I thought of a `/doc` section with examples. Others have thought they should go in `uw-ui-toolkit`. I'm not sure, but I'd love everyone's input.

Thanks,

Tim

**Comment by nblair** [comment]
What about using github pages?

**Comment by timlevett** [comment]
That could be neat @nblair . Keeps the documentation in the repo, kind of.

**Comment by jhanstra** [comment]
FYI, I'm currently working on adding our recent widget templates to the uw-ui-toolkit. But I don't think that's directly related to documentation on directives. I like the idea of a docs folder with markdown files in it for directives and other code documentation.

**Comment by timlevett** [comment]
Awesome @jhanstra ! I was also thinking of incorporating those templates into the widget creator somehow.

**Comment by apetro** [comment]
My big hangup on GitHub pages (vs a docs directory) is that GitHub pages and its separate branch misses an opportunity to have the documentation in the same branches with and versioned with the thing documented.  It's a beautiful thing in staving off technical debt when a commit that changes a thing can also include updating the documentation of the thing.

**Comment by timlevett** [comment]
What if... we put all the md (or jekell, whatever) in `/docs` then we had a job that saw the change on master, copied it to gh-pages, and pushed to gh-pages.

**Comment by timlevett** [comment]
Created `/docs` as a static frame application. Master docs are deployed gh-pages branch via Jenkins script.
