### ISSUE TITLE
Make settings less hardcoded

### ISSUE THREAD

**Issue by timlevett** [UW-Madison-DoIT/uw-frame#73]
Right now we have a `/settings` page. Its mostly for setting/removing flags to enable alpha features. So you can ship a 1/2 built feature for demo purposes. `angularjs-portal` has been abusing the frame page for some time for things that are just relevant to it. We recently created a `/settings/web` to kind of fix that, but I had the thought that "this could be better".

I would like to propose we move this to a config file. This way apps can use this page as well. We could have a frame constant file that would provide the frame flags. Then give the opportunity to expand upon them in an app level config.

**Comment by timlevett** [comment]
Current view of settings

![http://goo.gl/84wNMq](http://goo.gl/84wNMq)

**Comment by vertein** [comment]
:+1:   great idea
