### ISSUE TITLE
"File not found" view

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/uw-frame#86]
As a person interacting with a frame app,
I'd like a helpful error message when I click on a broken link instead of magically being redirected to the default route
so that I'm not confused by the application when there is a broken link.

Similar to the `/access-denied` route and issue #85 we have need to display a view for broken links that return 404. At present, the default route handles the request, and the user ends up at the landing page for the app, without any explanation.

**Comment by timlevett** [comment]
Interesting. We have a global 404 page already generated by https://git.doit.wisc.edu/myuw/my-root/

**Comment by timlevett** [comment]
But that would be good in case you click on a link w/in your app that does the angular router stuff.
