### ISSUE TITLE
Changing the constant NAMES.title results in changing the placeholder in the search bar

### ISSUE THREAD

**Issue by nblair** [UW-Madison-DoIT/uw-frame#89]
Here's the story version:

    As a developer
    I want to change the constant `NAMES.title`
    so that views like 'access-denied' and 'server-error' show my app's name.

If I change `NAMES.title` to "Staff Time and Reporting, the placeholder text in the search bar in the top nav changes to "Search Staff Time and Reporting" which I'm guessing is undesirable.

Would it seem sensible at present to change the placeholder text in the search bar to just a fixed 'Search MyUW' rather than being parameter-izable?

**Comment by timlevett** [comment]
We moved the MyUW title to the theme. We should find all frame level titles and move them to the theme.title

**Comment by apetro** [comment]
For academic purposes, here's a shot at a story for this from the user's perspective:

> As a user, I would like views like `access-denied` and `server-error` to reflect the name of the app I'm failing to access, so that I can better understand and potentially recover from the error.

I've liked some of what Ron Jeffries has to say about user stories.

For practical purposes, @timlevett 's solution sounds great. :smile:

**Comment by nblair** [comment]
:+1:

**Comment by paulerickson** [comment]
:+1:
